server:
  port: 9090
spring:
  application:
    name: greeter-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8008/realms/greeter
          jwk-set-uri: http://keycloak:8000/realms/greeter/protocol/openid-connect/certs
management:
  server:
    port: 8090
    ssl:
      enabled: false
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
access-token:
  granted-authorities-claim: "[realm_access][roles]"
greeting-socket:
  refresh-rate-ms: 3000
